### ISSUE TITLE
Menu items classes and active flag not updating on pageload, because of caching

### ISSUE THREAD

**Issue by Soean** [assely/framework#21]
The Menu classes are cached, so the current page class is not updating on pageload.

**Comment by jedrzejchalubek** [comment]
Menu items classes and active flag not updating on pageload, because Menu class caches generated tree on lines https://github.com/assely/framework/blob/master/src/Assely/Menu/Menu.php#L88-L102. 

The only way around, that comes to my mind, is to remove caching. However that way, menu structure tree will be generated on each request. I don't think this will be noticeable unless it contain a lot of elements.

But developers should be aware of this and do caching by yourself (annotation in docs?).
